### ISSUE TITLE
Python-dotenv could not parse statement starting at line 3

### ISSUE THREAD

**Issue by ben476** [theskumar/python-dotenv#266] opened 2020-07-15 03:48 UTC
It doesn't seem to work when I have a . (full stop) in in one of the variables. It works perfectly fine when I remove the .

**Comment by bbc2** [comment] 2020-07-16 19:29
I can't reproduce the issue. Could you show an example that causes the problem so that I can understand and try it?

**Comment by bbc2** [comment] 2021-02-21 15:01
I'm closing this issue as there is no evidence that a problem exists in python-dotenv. Let us know if you have more information.

**Closed by bbc2** 2021-02-21 15:01 UTC
