### ISSUE TITLE
ManagedLibraryInstallFailed

### ISSUE THREAD

**Issue by jdnr** [theskumar/python-dotenv#226] opened 2020-01-20 14:47 UTC
I load this lib from Azure Databricks Tasks nested in Data Factory pipelines.

Today the Databricks tasks were failing. They started to fail when they first ran after the commit 3637b3e (v0.10.5) was pushed, 1h later.

The error I was getting is:

"java.lang.RuntimeException: ManagedLibraryInstallFailed: org.apache.spark.SparkException: Process List(/databricks/python/bin/pip, install, python-dotenv, --disable-pip-version-check) exited with code 2."

I worked around this error by forcing PYPI to load the previous version: 0.10.4

I'm **not** able to reproduce the issue form a Databricks Notebook, playing with the commands suggested in this link

[introducing databricks library utilities for notebooks](https://databricks.com/blog/2019/01/08/introducing-databricks-library-utilities-for-notebooks.html)

like so:

1. "$ dbutils.library.list()" shows:
[]

2. "$ dbutils.library.installPyPI('python-dotenv','0.10.5')" returns True and list() shows:
['PyPI:(python-dotenv)-(0.10.5)-(empty)-(empty)']

3. I then Clear the State of the Notebook and repeat for 'python-dotenv' without version.  I get True and list() shows:
['PyPI:(python-dotenv)-(empty)-(empty)-(empty)']

4. I do a final test.  Clear the State of the Notebook, then install v0.10.4.  No problem: True and list() shows:
['PyPI:(python-dotenv)-(0.10.4)-(empty)-(empty)']

I stopped forcing the version on python-dotenv on my Cluster, to see whether the Databricks tasks continued to fail.

And they failed.  The error says:

pip._vendor.pep517.wrappers.BackendUnavailable 

Please see attached for a full error.
[ManagedLibraryInstalFailed-error.pdf](https://github.com/theskumar/python-dotenv/files/4086633/ManagedLibraryInstalFailed-error.pdf)

The cluster runtime version is still supported by Azure:

5.5 LTS (includes Apache Spark 2.4.3, Scala 2.11)

**Comment by bbc2** [comment] 2020-01-21 19:14
Thank you for all these details!  According to those and the discussion in 3637b3e114b9a3084457594ccfa3cb3e6d3d4ee4, it looks like your problem might have been caused by the lack of an uploaded wheel in PyPI, which I have now fixed.

Does it work for you now?

**Comment by bbc2** [comment] 2020-04-12 07:59
I assume this is fixed now so I'm closing this issue. Let us know if your problem wasn't solved.

**Closed by bbc2** 2020-04-12 07:59 UTC
