### ISSUE TITLE
Deployment issue, django on IIS

### ISSUE THREAD

**Issue by ssandr1kka** [theskumar/python-dotenv#305] opened 2021-02-10 11:22 UTC
Hi, 
First of all, thank you for this library and I hope I can get the help so I can make it work.
I have followed the instructions to set up dotenv and it works perfectly on my localhost.
However, when I send that exact code to AWS Microsoft IIS, to host the web it crashes.
Unfortunately, I cannot access traceback to see what is the issue, all I get is "Server 500 error"
Then I manually tried to step by step, follow instructions and configure code over AWS server.
I found out that the code crashes when I write 
"load_dotenv()"
![image](https://user-images.githubusercontent.com/67190400/107503661-e40f1600-6ba2-11eb-8b64-0deee6ed4ad1.png)
I have no idea of how to make it work... 
Please help?
https://github.com/ssandr1kka/StudioKuzaneli

**Comment by bbc2** [comment] 2021-02-10 12:32
Hi, is this problem linked to python-dotenv in any way?

**Comment by ssandr1kka** [comment] 2021-02-10 12:39
Then what would be the cause of the problem? The app crushes when I am trying to load_dotenv() which comes from python_dotenv library

**Comment by bbc2** [comment] 2021-02-10 15:14
I'm afraid I won't be able to help without a stack trace or other debugging information.  Even if the problem only appears when you add `load_dotenv()`, it might be caused by something other than python-dotenv.

**Comment by xqlip** [comment] 2021-02-18 01:25
Hi, you should check your .env path? 
![image](https://user-images.githubusercontent.com/35887727/108289928-4cc14880-71ca-11eb-921e-518f9bab7e91.png)
if does not work? 
you can use django-dotenv or provide debugging information.

**Comment by bbc2** [comment] 2021-05-13 10:12
We lack information to be able to conclude that there is a problem in Python-dotenv so I'll close this issue.  Let us know if you have more information about this.

**Closed by bbc2** 2021-05-13 10:12 UTC
