### ISSUE TITLE
wrong package in docker container

### ISSUE THREAD

**Issue by jon-butterworth** [theskumar/python-dotenv#283] opened 2020-10-30 08:15 UTC
I seem to be seeing a situation where `python-dotenv` shows a different package in a docker container to in my terminal, and subsequently does not work in the container. 

Docker file:

    FROM python:latest
    WORKDIR /casp
    COPY requirements.txt .
    RUN pip install -r requirements.txt
    COPY . /casp
    ENTRYPOINT [ "python3" ]
    CMD [ "main.py" ]

In my python app:

    from pathlib import Path
    from dotenv import load_dotenv
    
    env_path = Path('.') / '.env'
    load_dotenv(dotenv_path=env_path)

I actually tried abandoning this idea completely, and reverting to passing the environment variables in using `docker run -e` but, it turns out `Flask` relies on `dot_env` also, and as such it fails there also.

Error I'm seeing is:

`ImportError: cannot import name 'load_dotenv' from 'dotenv' (/usr/local/lib/python3.9/site-packages/dotenv/__init__.py)`

From within the *container*:

    >>> import dotenv
    >>> dir(dotenv)
    ['__author__', '__builtins__', '__cached__', '__doc__', '__email__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_get_line_', 'ast', 'get', 'load', 'os', 'save']

From within the venv in my *terminal*:

    >>> import dotenv
    >>> dir(dotenv)
    ['IS_TYPE_CHECKING', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'compat', 'dotenv_values', 'find_dotenv', 'get_cli_string', 'get_key', 'load_dotenv', 'load_ipython_extension', 'main', 'parser', 'set_key', 'unset_key']

As we can see, in the container it's `load` and in the terminal it's `load_dotenv`. More importantly, it's different! Using the exact same version in `requirements.txt` 

**Terminal:**

    (venv) jon@jon-Blade:~/PycharmProjects/caspv2$ pip freeze | grep dotenv
    python-dotenv==0.14.0

**Container:**

    root@2476f65ffa10:/casp# pip freeze | grep dotenv
    python-dotenv==0.14.0

Version from **Terminal**:

    (venv) jon@jon-Blade:~/PycharmProjects/caspv2$ python --version
    Python 3.8.5

Version from **Container**:

    root@3aa5c393846e:~# python --version
    Python 3.8.5

Running `pip show python-dotenv` on both also confirms the exact same details, line for line!

In the container I upgraded `python-dotenv` to `0.15.0`:

    root@8a94c1e22b8a:~# pip show python-dotenv | grep -i version
    Version: 0.15.0

However:

    >>> import dotenv
    >>> dir(dotenv)
    ['__author__', '__builtins__', '__cached__', '__doc__', '__email__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_get_line_', 'ast', 'get', 'load', 'os', 'save']

It's still giving me the wrong package.

**Comment by jon-butterworth** [comment] 2020-10-30 08:59
Strangely if I remove `python-dotenv` from my `requirements.txt` and then install it using the `upgrade` flag in my Dockerfile:

```
RUN pip install -r requirements.txt
RUN pip install -U python-dotenv

```
...it then works as expected and I see the correct package from `dir(dotenv)`:

```
>>> import dotenv
>>> dir(dotenv)
['IS_TYPE_CHECKING', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'compat', 'dotenv_values', 'find_dotenv', 'get_cli_string', 'get_key', 'load_dotenv', 'load_ipython_extension', 'main', 'parser', 'set_key', 'unset_key']
```
This has resolved my immediate problem, but it seems strange that `pip install python-dotenv` and `pip install -U python-dotenv` would install different packages.. but only within a docker container!? As previously mentioned in my terminal, running the exact same version of everything... `pip install python-dotenv` works as expected.

**Comment by bbc2** [comment] 2020-10-30 14:23
I don't understand why you have a problem and I can't reproduce your issue. Could you show me a reproducible minimal example?

**Comment by sanders41** [comment] 2020-11-14 19:16
Have you tried running `docker build`? In your Dockerfile you have `FROM python:latest` which according to docker hub is currently 3.9.0, but your output shows you have 3.8.5. Your error message is also referencing python 3.9 so maybe that is the problem?

**Comment by bbc2** [comment] 2021-02-21 14:29
I'm closing this as there is no indication that a problem exists in python-dotenv.  Let us know if you have more information.

**Closed by bbc2** 2021-02-21 14:29 UTC
