### ISSUE TITLE
pyinstaller doesn't find .env file 

### ISSUE THREAD

**Issue by nubianlachlan** [theskumar/python-dotenv#259] opened 2020-07-01 15:29 UTC
It seems that pyinstaller cannot read .env file in root when script in subfolder calls it. 
e.g. 

    └── .env
    └── app.py
    └── module
          └── sql_config.py
        
Re - https://github.com/theskumar/python-dotenv/commit/a1bdf79da6b618f3e6a6fb1be4de8fea77e23708
any idea how to overcome this?

These strategies don't seem to work: 

```
# settings.py
from dotenv import load_dotenv
load_dotenv()

# OR, the same with increased verbosity
load_dotenv(verbose=True)

# OR, explicitly providing path to '.env'
from pathlib import Path  # Python 3.6+ only
env_path = Path('.') / '.env'
load_dotenv(dotenv_path=env_path)
```

**Comment by bbc2** [comment] 2020-07-25 18:39
I'm afraid I don't understand what your problem is. Could you be more specific, maybe show some of the content of your code and how you are executing it?

With or without Pyinstaller, you should be able to load the `.env` from anywhere with the `dotenv_path` argument.  The commit you referred to just changed what happens when the `dotenv_path` (or `stream`) argument is not specified.

**Comment by LordST95** [comment] 2021-02-01 05:45
this is my project's structure:

.
├── commandHandlers
│   ├── basics.py
│   ├── __init__.py
├── dbHelper.py
├── __init__.py
├── main.py
├── .env
├── requirements.txt
├── responseTexts
│   ├── agreementResponces.py
│   ├── basicResponces.py
│   ├── __init__.py
│   ├── locales
│   │   ├── default.pot
│   │   ├── fa
│   │   │   └── LC_MESSAGES
│   │   │       ├── default.mo
│   │   │       └── default.po
│   │   └── ReadMe.md



And this is how I read those files:
- load_dotenv(dotenv_path=".env")
- localedir = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'locales')


if I print localedir before and after the build, it will be 
`
...../MyProject/responseTexts/locales
`
and
`
/tmp/_MEIXPRtp4/responseTexts/locales
`

As u know, the problem caused by abstractPath and can be fixed by changing it to a relative approach and put those files (".env" and "responseTexts/") next to generated exe file, But I want to say that will be a good idea to compact .env files and locals file into the generated file as we use '--onefile' option and we except only one file as our output ;)

**Comment by LordST95** [comment] 2021-02-01 13:41
@nubianlachlan you can follow the conversation on [here](https://github.com/pyinstaller/pyinstaller/issues/5522#issuecomment-770858489). I tell the solution there.

**Comment by bbc2** [comment] 2021-02-21 14:28
I'm closing this as it doesn't seem to be a problem anymore.

**Closed by bbc2** 2021-02-21 14:28 UTC
