### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by IamKraZ** [theskumar/python-dotenv#273] opened 2020-08-30 03:35 UTC
I was following a tutorial that uses your .dotenv library, but after pip installing it I got the dreaded:
ModuleNotFoundError: No module named 'dotenv'. 

I pip installed it using: pip install -U python-dotenv

but when I run my python file I get that error.

this is my code so far:
# test.py
import os
from dotenv import load_dotenv

load_dotenv()

it errors on line #3 saying "ModuleNotFoundError: No module named 'dotenv'". 

Any help would be greatly appreciated :)

**Comment by bbc2** [comment] 2020-08-30 07:22
It looks like this problem is not specific to python-dotenv.  Could you check if other packages work?  Perhaps pip is not installing packages where python can find them.  It's a common issue.

**Comment by IamKraZ** [comment] 2020-08-30 16:16
Ah, it showed that it installed it, but i don't know where.

I can try and find out where it installed to and see.

I just did a "pip" install. I have no idea what came with it, lol. So I
dont know what to try.

**Comment by IamKraZ** [comment] 2020-08-30 16:17
I have installed other packages like discord, and pygame and others. They
all work fine.

**Comment by tourdownunder** [comment] 2020-12-05 09:01
I'm also having this issue within a jupyter labs.

<img width="535" alt="Screen Shot 2020-12-05 at 7 52 53 pm" src="https://user-images.githubusercontent.com/829044/101238366-d7e68280-3733-11eb-8d6d-268b6fd6134a.png">
![Screen Shot 2020-12-05 at 7 53 08 pm](https://user-images.githubusercontent.com/829044/101238367-da48dc80-3733-11eb-936a-23c592f4d62b.png)

Though as a precaution I switched across to jupyter notebook and it does work as expected.

**Comment by bbc2** [comment] 2020-12-05 13:52
Thanks for the reports.  Unfortunately, I don't know what to suggest since python-dotenv is packaged like any other package as far as I know, and I can't reproduce your issue (either in the console or in JupyterLab).  Please let us know if you have more information about what could cause your issue.

**Comment by mdhannaff** [comment] 2021-01-22 22:45
I had the same issue (Python 3.8.5, dotenv 0.15.0) and was getting `ModuleNotFoundError: No module named 'dotenv'` in both the console and JupyterLab.  All other packages seemed to install via pip with no problems.

I just ran:

```
pip3 uninstall python-dotenv
pip3 install -U python-dotenv
```

This fixed my problem.

**Comment by bbc2** [comment] 2021-05-13 10:09
There doesn't seem to be anything we can do about this so I'll close the issue.  Let us know if you get more information about that particular problem.

**Closed by bbc2** 2021-05-13 10:09 UTC

**Comment by mehrdad-khojastefar** [comment] 2022-01-20 21:45
A workaround is using python 3.6 as your virtualenv python.

**Comment by jeremyyma** [comment] 2022-02-27 23:51
For macOS, you will need to install with below:

python -m pip install python-dotenv

**Comment by naruto0uzamaki** [comment] 2022-03-21 21:01
python3 -m pip install python-dotenv

 this worked for me.

**Comment by KarelLangeraar** [comment] 2023-05-08 10:20
python3 -m pip install -r requirements.txt

This will install all missing modules...
