### ISSUE TITLE
Does not load from current directory

### ISSUE THREAD

**Issue by RazerM** [theskumar/python-dotenv#108] opened 2018-04-27 11:41 UTC
The README states (emphasis mine)

> The easiest and most common usage consists on calling `load_dotenv` when the application starts, which will load environment variables **from a file named .env in the current directory**

I'm not finding this to be the case. `load_dotenv` defaults to calling `find_dotenv()`:

https://github.com/theskumar/python-dotenv/blob/b20d818c9296817352f5d0d7cb7b8acd90a2548d/dotenv/main.py#L249-L251

but `usecwd` defaults to `False`:

https://github.com/theskumar/python-dotenv/blob/b20d818c9296817352f5d0d7cb7b8acd90a2548d/dotenv/main.py#L224-L246

In my case, path becomes '\<venv path>/lib/python3.6/site-packages/dotenv' on line 236 so the current directory is never traversed.

**Comment by cjauvin** [comment] 2018-04-27 14:07
I confirm, I'm trying this package for the first time this morning (I learned about its existence through Flask 1.0's announcement yesterday), and the only way to make it work in my context is to manually set `usecwd` to `True`, there:

https://github.com/theskumar/python-dotenv/blob/master/dotenv/main.py#L250

**Comment by jimdickinson** [comment] 2018-07-02 02:02
I think there was an assumption that the virtual environment would be rooted in the current working directory, which is often not the case. My problem is that pipenv puts the virtual environment in my home directory under a .local directory, so `frame_filename` is something like `$HOME/.local/share/virtualenvs/<projectname>-<hash>/lib/python2.7/site-packages/dotenv/main.py` when find_dotenv is called from load_dotenv. Calling `find_dotenv()` with no arguments in my code works, because then frame_filename is my calling code under the current working directory.

**Comment by ClintOxx** [comment] 2018-07-18 02:24
Yea I am running into the same exact problems they are having

**Comment by cjauvin** [comment] 2018-07-18 03:02
This should have been fixed by 5238808e215b3cbd227c228e0f7df74a3203515c, which was recently merged.

**Comment by theskumar** [comment] 2018-07-18 03:03
@cjauvin @ClintOxx i'll make a new release sometime today. Hope this helps. Else you can install the latest master and see if that fixes your issue.

**Comment by ClintOxx** [comment] 2018-07-18 03:04
@theskumar alright will do, thanks!

**Comment by djbriane** [comment] 2018-07-26 22:41
I'm running into the same issue on my Ubuntu server with Python 2.7 (had no problems in my local environment from the master branch) and had to use the following:

```python
BASE_DIR = os.path.abspath(os.path.dirname(__file__))
load_dotenv(dotenv_path=os.path.join(BASE_DIR, "/.env"))
```

I'm not familiar enough with Python to make a pull request but thought I'd share my workaround in case it helps anyone else.

**Comment by ClintOxx** [comment] 2018-07-26 22:46
Yea that was what I ended up doing as well @djbriane

**Comment by sloria** [comment] 2018-08-08 23:25
I've confirmed that loading from the current directory is working in 0.9.1.

```bash
# ./.env
FOO=bar
```

```python
# ./t.py
import os
from dotenv import load_dotenv

load_dotenv()

print(os.environ['FOO'])  # prints 'bar'
```

@theskumar I believe this issue can be closed.

**Comment by theskumar** [comment] 2018-08-09 11:34
Great thanks @sloria ! 👍

**Closed by theskumar** 2018-08-09 11:34 UTC

**Comment by codewithlennylen** [comment] 2021-02-17 18:23
The code below worked out for me after all the numerous solutions above failed to work out for me.
The **.env** file is in the same directory as the file below

**test.py**
```
import os
from dotenv import load_dotenv

basedir = os.path.abspath(os.path.dirname(__file__))
load_dotenv(os.path.join(basedir, '.env'))
```

**Comment by sanmai-NL** [comment] 2023-09-27 07:59
@sloria @theskumar This only works when the Python source file is in the current working directory. It doesn't work for packages installed in the system site packages.

**Comment by QwertyJack** [comment] 2024-04-30 15:16
I believe this is unexpected. When a third-party package mentions support for `.env`, users expect to configure variables using a `.env` file in the current directory rather than the site package directory.
