### ISSUE TITLE
find_dotenv() unable to find .env

### ISSUE THREAD

**Issue by scottlimmer** [theskumar/python-dotenv#130] opened 2018-08-27 02:13 UTC
find_dotenv() in 0.9.* is unable to find .env file in same directory as python script. Works if downgraded to 0.8.2.

**Comment by CSRaghunandan** [comment] 2018-09-26 10:45
I'm also having the same issue, while the older version worked perfectly fine.

I had to manually input the path of the `.env` file

**Comment by smsearcy** [comment] 2018-11-15 00:38
I encountered the same issue when running code where `site-packages` is outside of the path my code is using (when installed in a `venv` sub-directory the issue likely doesn't show up).  Using a debugger I think the issue is with 5238808 because the filename comparison isn't accounting for the difference in extension between a `.py` and `.pyc` file.

I'll work on a PR.

**Comment by smsearcy** [comment] 2018-11-15 02:06
Based on some further testing I'm only seeing the issue on Python 2.7, not 3.5 or above.  In Python 2.7 `__file__` will return a `.pyc` extension while the later versions appear to sanitize that to `.py` for consistency.

@scottlimmer or @CSRaghunandan, which versions of Python are you using?  (just to know if it is the same issue)

**Comment by scottlimmer** [comment] 2018-11-15 02:20
@smsearcy Python 2.7.5. Seems like you're onto something.

**Comment by theskumar** [comment] 2018-11-15 03:12
@smsearcy interesting! We would love a PR if you are still onto it.

**Comment by smsearcy** [comment] 2018-11-15 06:13
@theskumar thank you, I will try to get one put together in the next day or two to fix this issue.  I did find the [official comments](https://bugs.python.org/issue1762972) about changing how `__file__` worked between Python 2 and 3.

At this time I'm not sure how to create a test case without re-organizing the code base which seems a little out of scope for this issue.  If that is something that would be considered I can create a separate pull request for that.  For a little more background, here's [another article](https://hynek.me/articles/testing-packaging/) that shaped my thinking on the `src` folder and I've used his examples successfully.

**Closed** 2019-02-16 09:01 UTC

**Comment by kratsg** [comment] 2019-03-20 06:19
Hi all, i find that I've been hit with this bug for sure. Is it possible to release a tag of python-dotenv (and uploaded to pypi) that incorporates the fix? That would be great!

**Comment by kavmuni** [comment] 2019-06-30 09:09
Hi,

I am still not able to use the find_dotenv() to find the path of .env file.

The .env file is present in the same folder where my script is placed.

**Comment by theskumar** [comment] 2019-06-30 09:13
@kavmuni Please describe your OS and file structure and also file permissions.

**Comment by kavmuni** [comment] 2019-06-30 09:27
.env file and the actual script was placed in titanic_data_set and find_dotenv() was not working.

When .env is placed in the folder parent folder of titanic_data_set, it was able to find it.

OS: Windows 10

# Name                    Version                   Build  Channel
python-dotenv             0.10.3                   pypi_0    pypi


---------------------
$ ls -ltr
total 4628
drwxrwx---+ 1 Muniappan None       0 Apr 25 23:23 09
drwxrwx---+ 1 Muniappan None       0 Apr 25 23:23 08
drwxrwx---+ 1 Muniappan None       0 Apr 25 23:23 07
drwxrwx---+ 1 Muniappan None       0 Apr 25 23:23 06
drwxrwx---+ 1 Muniappan None       0 Apr 25 23:23 05
drwxrwx---+ 1 Muniappan None       0 Apr 25 23:23 04
drwxrwx---+ 1 Muniappan None       0 Apr 25 23:23 03
drwxrwx---+ 1 Muniappan None       0 Apr 25 23:23 02
-rwxrwx---+ 1 Muniappan None 4403348 Jun 29 13:28 python-understanding-machine-learning.zip
-rwxrwx---+ 1 Muniappan None  277298 Jun 29 13:30 MachineLearningWithPython-master.zip
drwxrwx---+ 1 Muniappan None       0 Jun 29 13:30 MachineLearningWithPython-master
-rwxrwx---+ 1 Muniappan None   20783 Jun 30 13:53 File_to_gunnvant.py
-rwxrwx---+ 1 Muniappan None   20858 Jun 30 14:03 Script_01.py
drwxrwx---+ 1 Muniappan None       0 Jun 30 14:42 titanic_data_set

---------------------
