### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by pressleydavid** [theskumar/python-dotenv#240] opened 2020-03-07 05:00 UTC
Whenever I install dotenv accoring to: `pip install -U python-dotenv`, and then attempt to import via: `from dotenv import load_dotenv`, I get the following error the first time I try to import the module: `ModuleNotFoundError: No module named 'dotenv'`

The issue  goes away when I re-source my venv on the command line, or reload my window in VS Code via `Developer: Reload Window`

I suppose all's well that ends well, but curious to understand the why?

**Comment by bbc2** [comment] 2020-03-08 09:30
I can't reproduce your problem. Are you sure it's specific to Python-dotenv?  It looks to me like this is a problem with how you activate your virtualenv and should also be an issue for other packages.

**Comment by ericrojo156** [comment] 2020-03-16 20:46
I am seeing the same issue

**Comment by llunn** [comment] 2020-03-29 17:44
This has something to do with multiple python versions installed, but I'm unable to pinpoint the actual problem.

For me, installing, uninstalling, reinstalling this that and other thing did not fix anything.

The solution was to run the script with the full path of the virtual environments version of python.  To find this, 

```bash
cd project_dir
source venv/bin/activate
which python
```

Then, executing the script with the full path that which reports worked. 

e.g. 

```bash

/usrdir/some_project/venv/bin/python3.7/pythong some_script.py
```

**Comment by bbc2** [comment] 2020-03-30 08:47
I'm closing this issue since it doesn't seem to be specific to Python-dotenv.

**Closed by bbc2** 2020-03-30 08:47 UTC

**Comment by anasmirza-ewebcore** [comment] 2020-04-07 09:30
Hi,

I'm having same issue on my mac, I'm not using any virtualenv.

Python version: 3.7.7

**Comment by bbc2** [comment] 2020-04-07 09:50
Please open a new issue if you can show that this is specific to python-dotenv.  If your problem occurs with other packages too, please use Python help forums.
